// <auto-generated />
using System;
using BarberShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShopAPI.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20260812173110_AddDataIntegrityCheckConstraints")]
    partial class AddDataIntegrityCheckConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberShopAPI.Models.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptsNewBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Barber_UserId");

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BarberSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BarberId")
                        .IsUnique()
                        .HasDatabaseName("UX_BarberSchedule_CurrentVersion")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("BarberId", "EffectiveFrom");

                    b.ToTable("BarberSchedules");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BarberScheduleShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BarberScheduleId");

                    b.ToTable("BarberScheduleShifts", t =>
                        {
                            t.HasCheckConstraint("CK_BarberScheduleShifts_DayOfWeek", "[DayOfWeek] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_BarberScheduleShifts_StartBeforeEnd", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("CancellationReason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<bool>("OutsideBarberSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("OutsideShopHours")
                        .HasColumnType("bit");

                    b.Property<int?>("OverriddenByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReminderJobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverriddenByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("BarberId", "StartDateTime")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BookingService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServices");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'CASH'");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payment_BookingId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payment_StripePaymentIntentId")
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] IS NULL OR ([Amount] > 0 AND [Amount] <= 400)");
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Service_Name")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BarberShopAPI.Models.ShopClosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarberId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate")
                        .IsUnique()
                        .HasFilter("[BarberId] IS NULL AND [IsFullDay] = 1 AND [IsActive] = 1");

                    b.HasIndex("BarberId", "StartDate", "EndDate")
                        .IsUnique()
                        .HasFilter("[BarberId] IS NOT NULL AND [IsFullDay] = 1 AND [IsActive] = 1");

                    b.ToTable("ShopClosures");
                });

            modelBuilder.Entity("BarberShopAPI.Models.ShopHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("ShopHours", t =>
                        {
                            t.HasCheckConstraint("CK_ShopHours_OpenBeforeClose", "[IsClosed] = 1 OR [OpenTime] < [CloseTime]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 0,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 1,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CloseTime = new TimeOnly(17, 30, 0),
                            DayOfWeek = 6,
                            IsClosed = false,
                            OpenTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Models.ShopSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BufferMin")
                        .HasColumnType("int");

                    b.Property<int>("DefaultAdminBookingDurationMin")
                        .HasColumnType("int");

                    b.Property<int>("GraceMinutesAfterClose")
                        .HasColumnType("int");

                    b.Property<int>("MaxAdvanceBookingDays")
                        .HasColumnType("int");

                    b.Property<int>("MinAdvanceBookingMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RefundCutoffHours")
                        .HasColumnType("int");

                    b.Property<int>("SlotStepMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ShopSettings_BufferMin", "[BufferMin] BETWEEN 0 AND 120");

                            t.HasCheckConstraint("CK_ShopSettings_DefaultAdminBookingDurationMin", "[DefaultAdminBookingDurationMin] BETWEEN 5 AND 240");

                            t.HasCheckConstraint("CK_ShopSettings_GraceMinutesAfterClose", "[GraceMinutesAfterClose] BETWEEN 0 AND 120");

                            t.HasCheckConstraint("CK_ShopSettings_MaxAdvanceBookingDays", "[MaxAdvanceBookingDays] BETWEEN 1 AND 365");

                            t.HasCheckConstraint("CK_ShopSettings_MinAdvanceBookingMinutes", "[MinAdvanceBookingMinutes] BETWEEN 0 AND 1440");

                            t.HasCheckConstraint("CK_ShopSettings_RefundCutoffHours", "[RefundCutoffHours] BETWEEN 0 AND 168");

                            t.HasCheckConstraint("CK_ShopSettings_SlotStepMin", "[SlotStepMin] IN (5, 10, 15, 20, 30)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BufferMin = 0,
                            DefaultAdminBookingDurationMin = 30,
                            GraceMinutesAfterClose = 0,
                            MaxAdvanceBookingDays = 60,
                            MinAdvanceBookingMinutes = 90,
                            RefundCutoffHours = 24,
                            SlotStepMin = 30
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Phone")
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Barber", b =>
                {
                    b.HasOne("BarberShopAPI.Models.User", "User")
                        .WithOne("Barber")
                        .HasForeignKey("BarberShopAPI.Models.Barber", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BarberSchedule", b =>
                {
                    b.HasOne("BarberShopAPI.Models.Barber", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BarberScheduleShift", b =>
                {
                    b.HasOne("BarberShopAPI.Models.BarberSchedule", "Schedule")
                        .WithMany("Shifts")
                        .HasForeignKey("BarberScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Booking", b =>
                {
                    b.HasOne("BarberShopAPI.Models.Barber", "Barber")
                        .WithMany("Bookings")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShopAPI.Models.User", "OverriddenBy")
                        .WithMany()
                        .HasForeignKey("OverriddenByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarberShopAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");

                    b.Navigation("Barber");

                    b.Navigation("OverriddenBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BookingService", b =>
                {
                    b.HasOne("BarberShopAPI.Models.Booking", "Booking")
                        .WithMany("Services")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShopAPI.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Payment", b =>
                {
                    b.HasOne("BarberShopAPI.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("BarberShopAPI.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BarberShopAPI.Models.ShopClosure", b =>
                {
                    b.HasOne("BarberShopAPI.Models.Barber", "Barber")
                        .WithMany("Closures")
                        .HasForeignKey("BarberId");

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Barber", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Closures");
                });

            modelBuilder.Entity("BarberShopAPI.Models.BarberSchedule", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BarberShopAPI.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BarberShopAPI.Models.User", b =>
                {
                    b.Navigation("Barber");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
